SAVINGS_GAME_CONFIG = {
    'low': {
        'INITIAL_CASH': 25,
        'INITIAL_FOOD': 0,
        'INITIAL_SALARY': 4.00,
        'INITIAL_FOOD_PRICE': 4.20,
        'SAVINGS_INTEREST_RATE': 0.019,
        'ASSET_EXPECTED_RETURN': 0.06,
        'ASSET_STANDARD_DEVIATION': 0.1,
        'INFLATION_RATE': 0.05
    },
    'high': {
        'INITIAL_CASH': 25,
        'INITIAL_FOOD': 0,
        'INITIAL_SALARY': 4.00,
        'INITIAL_FOOD_PRICE': 4.20,
        'SAVINGS_INTEREST_RATE': 0.019,
        'ASSET_EXPECTED_RETURN': 0.06,
        'ASSET_STANDARD_DEVIATION': 0.1,
        'INFLATION_RATE': 0.15
    }
}